### ISSUE TITLE
Button design and behaviour

### ISSUE THREAD

**Issue by r0b0k1d** [re-nft/front#84]
### Buttons look and act wrong.

Current state:
![Screenshot 2021-06-04 at 15 49 21](https://user-images.githubusercontent.com/77438706/120811662-8127fd00-c54c-11eb-8119-a9e03a149202.png)

Supposed to look like this:
![Screenshot 2021-06-04 at 15 49 25](https://user-images.githubusercontent.com/77438706/120811753-9c930800-c54c-11eb-83dd-3c93ddb4a821.png)

Correct Font: Press Start 2P Regular, Size 14px

ColorsCodes:
Purple #9966cc
Orange #ff9800

The Button is supposed to mimic a real button. It gets pushed in and doesn't change size.
Black border base (4px) doesn't change.

**Applies to all Buttons including checkbox**

**Comment by r0b0k1d** [comment]
![image](https://user-images.githubusercontent.com/77438706/127144584-ed56204f-f30d-4190-bce0-487f4a335c8f.png)

**Comment by eenagy** [comment]
Done
