### ISSUE TITLE
Renting/Lending Headlines

### ISSUE THREAD

**Issue by r0b0k1d** [re-nft/front#90]
Please use these:
<img width="1035" alt="Screenshot 2021-06-04 at 17 14 54" src="https://user-images.githubusercontent.com/77438706/120824151-71aeb100-c558-11eb-8aee-ae75f36605a9.png">
[210604_rentinglending.zip](https://github.com/re-nft/front/files/6599506/210604_rentinglending.zip)

**Comment by eenagy** [comment]
Done
